import React, { useEffect, useMemo, useState } from 'react'
import lessons from './data.json'
import { chapters, cases } from './chapters.js'
import './styles.css'

const lang = import.meta.env.VITE_SITE_LANG === 'en' ? 'en' : 'zh'
const zh = lang === 'zh'
const sibling = zh ? 'https://gmyoung.github.io/iwcc-handbook-en/' : 'https://gmyoung.github.io/iwcc-handbook-zh/'
const handbook = 'https://iwcc.illinois.gov/content/dam/soi/en/web/iwcc/documents/handbook/IWCC%20handbook%2006.06.24.pdf'
const sourceIndex = 'https://iwcc.illinois.gov/about/handbook.html'
const compfile = 'https://iwcc.illinois.gov/resources/resources-for-pro-se.html'
const schedule = [
  ['Thumb','拇指','70','76','70','76','76'],['Index finger','食指','40','43','40','43','43'],['Middle finger','中指','35','38','35','38','38'],['Ring finger','无名指','25','27','25','27','27'],['Little finger','小指','20','22','20','22','22'],['Great toe','大脚趾','35','38','35','38','38'],['Each other toe','其他每个脚趾','12','13','12','13','13'],['Hand','手','190','205','190','205','205'],['Carpal tunnel, repetitive trauma','重复创伤性腕管综合征','—','—','—','—','28.5–57'],['Arm','手臂','235','253','235','253','253'],['Above-elbow amputation','肘上截肢','250','270','250','270','270'],['Shoulder-joint amputation','肩关节截肢','300','323','300','323','323'],['Foot','脚','155','167','155','167','167'],['Leg','腿','200','215','200','215','215'],['Above-knee amputation','膝上截肢','225','242','225','242','242'],['Hip-joint amputation','髋关节截肢','275','296','275','296','296'],['Eye','眼','150','162','150','162','162'],['Eye removal','眼球摘除','160','173','160','173','173'],['Hearing, one ear','单耳听力损失','50','54','50','54','54'],['Hearing, both ears','双耳听力损失','200','215','200','215','215'],['One testicle','一侧睾丸','50','54','50','54','54'],['Both testicles','双侧睾丸','150','162','150','162','162']
]
const sectionLessons = n => lessons.filter(x => x.section === n)
const title = item => zh ? item.zhTitle : item.enTitle
const summary = item => zh ? item.zhSummary : item.enSummary
const detail = item => zh ? item.zhDetail : item.enDetail
const labels = zh ? {
  book:'伊利诺伊工伤手册', edition:'2024 修订版 · 中文导读', chapters:'章节', search:'搜索具体问题', progress:'学习进度', home:'从第一章开始', lesson:'知识点', read:'进入阅读', next:'下一条', previous:'上一条', done:'标记已学会', learned:'已学会', story:'一个人怎样用到这条规则', storyNote:'标有“虚构教学情境”的故事用于解释规则；真实判例附法院原文。', rule:'直接读懂这条规则', key:'先抓住这一句', interactive:'动手试一试', source:'依据', current:'IWCC 2024 修订版', case:'真实判例', opinion:'查看法院判决', chapter:'返回本章', all:'全部章节', menu:'打开目录', close:'关闭目录', results:'搜索结果', noResults:'没有找到对应知识点', prevChapter:'上一章', nextChapter:'下一章', footnote:'教学阅读材料。个案结论仍取决于事实、证据和现行法律。', start:'开始阅读', overview:'这一章要学什么', lines:'知识点', jump:'继续阅读', apply:'把规则放进情境', count:'条', learn:'已学', font:'字号', language:'English', verify:'官方发布页'
} : {
  book:'Illinois Work Comp Handbook', edition:'2024 revision · reading edition', chapters:'Chapters', search:'Search a specific rule', progress:'Reading progress', home:'Start with chapter one', lesson:'Lesson', read:'Read lesson', next:'Next lesson', previous:'Previous', done:'Mark learned', learned:'Learned', story:'How one person used this rule', storyNote:'Stories labeled fictional are teaching examples. Actual cases link to the court opinion.', rule:'Read the rule in full', key:'The point to remember', interactive:'Try the rule', source:'Source', current:'IWCC 2024 revision', case:'Actual court case', opinion:'Read court opinion', chapter:'Back to chapter', all:'All chapters', menu:'Open chapters', close:'Close chapters', results:'Search results', noResults:'No matching lessons', prevChapter:'Previous chapter', nextChapter:'Next chapter', footnote:'Educational reading material. Individual outcomes depend on facts, evidence, and current law.', start:'Start reading', overview:'What this chapter teaches', lines:'lessons', jump:'Continue reading', apply:'Put the rule into a situation', count:'', learn:'learned', font:'Text size', language:'中文', verify:'Official handbook page'
}

function routeFromHash() {
  const path = decodeURIComponent(window.location.hash.replace(/^#\/?/, ''))
  const lesson = path.match(/^lesson\/(\d+\.\d+)$/) || path.match(/^lesson=(\d+\.\d+)$/)
  if (lesson && lessons.some(x => x.id === lesson[1])) return {type:'lesson', id:lesson[1]}
  const chapter = path.match(/^chapter\/(\d+)$/)
  if (chapter && +chapter[1] >= 1 && +chapter[1] <= 11) return {type:'chapter', section:+chapter[1]}
  return {type:'chapter', section:1}
}
function go(path) { window.location.hash = '#/' + path }
function chapterPath(n) { return `chapter/${n}` }
function lessonPath(id) { return `lesson/${id}` }
function splitCopy(text) {
  if (zh) {
    const parts = text.match(/[^。！？]+[。！？]?/g) || [text]
    const out = []
    for (let i=0;i<parts.length;i+=2) out.push(parts.slice(i,i+2).join(''))
    return out.filter(Boolean)
  }
  const parts = text.split(/(?<=[.!?])\s+(?=[A-Z(])/)
  const out=[]; let buffer=''
  for (const part of parts) { if ((buffer+part).length>360 && buffer) {out.push(buffer);buffer=''} buffer+=(buffer?' ':'')+part }
  if (buffer) out.push(buffer)
  return out
}

function NumberInput({label,value,set,min=0,max=100000}) {
  return <label className="lab-field"><span>{label}</span><input type="number" value={value} min={min} max={max} onChange={e=>set(Number(e.target.value))} /></label>
}
function Toggle({on,onChange,children}) { return <button type="button" className={'toggle-chip '+(on?'active':'')} onClick={()=>onChange(!on)} aria-pressed={on}>{children}<span>{on?'✓':'+'}</span></button> }
function Lab({section}) {
  const [a,setA]=useState(false), [b,setB]=useState(false), [c,setC]=useState(false)
  const [day,setDay]=useState(20), [wage,setWage]=useState(900), [light,setLight]=useState(500), [weeks,setWeeks]=useState(253), [loss,setLoss]=useState(20)
  const pick=(z,e)=>zh?z:e
  const money=n=>'$'+Math.max(0,n).toLocaleString(lang==='zh'?'zh-CN':'en-US',{maximumFractionDigits:2,minimumFractionDigits:2})
  const note=<p className="lab-note">{pick('演示只解释判断顺序；法定上下限、事故日期及个案证据可能改变结果。','This teaches the decision sequence; legal limits, injury date, and evidence may change the result.')}</p>
  if (section===1) return <div className="lab-content"><p>{pick('点亮两项事实，看为什么“在公司受伤”并非完整结论。','Turn on both facts to see why “hurt at work” is not the complete test.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('存在雇佣关系','Employment relationship')}</Toggle><Toggle on={b} onChange={setB}>{pick('伤害因工作而起','Injury arose from work')}</Toggle></div><div className="lab-result">{a&&b?pick('具备两个基础环节；仍要核对通知、因果关系与具体福利。','Two foundational links are present. Notice, causation, and the requested benefit still need proof.'):pick('还缺少关键事实。补充证据后才能继续判断福利。','A key fact remains missing. Gather proof before deciding the benefit.')}</div>{note}</div>
  if (section===2) return <div className="lab-content"><p>{pick('假设普通事故发生在第 0 天。拖动员工通知时间。','Suppose an ordinary accident occurred on day 0. Move the notice date.')}</p><label className="slider-label">{pick('通知雇主：第','Notice to employer: day')} <strong>{day}</strong> {pick('天','')}<input type="range" min="0" max="60" value={day} onChange={e=>setDay(+e.target.value)} /></label><div className="timeline-meter"><span style={{width:`${Math.min(day/60*100,100)}%`}} /></div><div className="lab-result">{day<=45?pick('仍在普通事故通常的 45 天窗口内；越早通知越容易留下证据。','Within the usual 45-day window for an ordinary accident; earlier notice is easier to prove.'):pick('已超过普通事故通常的 45 天窗口。职业病等有不同起算规则。','Beyond the usual ordinary-accident window. Occupational disease and other exposures have different rules.')}</div>{note}</div>
  if (section===3) return <div className="lab-content"><p>{pick('这三个动作分别解决不同问题，点选已经完成的动作。','These three actions solve different problems. Select the steps already completed.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('通知雇主','Notify employer')}</Toggle><Toggle on={b} onChange={setB}>{pick('雇主报事故','Employer accident report')}</Toggle><Toggle on={c} onChange={setC}>{pick('CompFile 正式立案','File in CompFile')}</Toggle></div><div className="lab-result">{c?pick('有正式申请记录；保存回执并继续跟进案件。','A formal application is on file. Save the receipt and keep the case moving.'):pick('尚未完成正式立案。前两个动作不能代替 CompFile 申请。','No formal claim has been filed. The first two actions do not replace the CompFile application.')}</div><a className="lab-link" href={compfile} target="_blank" rel="noreferrer">CompFile / IWCC ↗</a></div>
  if (section===4) return <div className="lab-content"><p>{pick('林娜准备听证：把需要证明的五个环节点亮。','Lina prepares for a hearing. Turn on the five links she must prove.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('雇佣与工作事故','Employment & event')}</Toggle><Toggle on={b} onChange={setB}>{pick('医学因果关系','Medical causation')}</Toggle><Toggle on={c} onChange={setC}>{pick('及时通知','Timely notice')}</Toggle></div><div className="lab-result">{[a,b,c].filter(Boolean).length}/3 · {a&&b&&c?pick('基础证据链成形；还要核对管辖、工资和福利程度。','The core record is taking shape. Jurisdiction, wage, and benefit extent still matter.'):pick('证据链仍有空缺；结论应由事实和医疗记录支撑。','The proof chain has gaps; facts and medical records must support the claim.')}</div></div>
  if (section===5) return <div className="lab-content"><p>{pick('试着改变医疗路径。急诊与符合规则的转诊通常不占独立选医次数。','Try a care path. Emergency care and qualifying referrals generally do not use independent provider choices.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('雇主设有 PPP','Employer has a PPP')}</Toggle><Toggle on={b} onChange={setB}>{pick('书面退出 PPP','Decline PPP in writing')}</Toggle></div><div className="lab-result">{a&&b?pick('退出计作一次选择；另开独立治疗链前，先核对雇主批准要求。','Declining uses one choice; check approval before starting another independent treatment chain.'):a?pick('通常可在 PPP 网络内作两次独立选择。','Generally two independent choices are available within the PPP network.'):pick('没有 PPP 时，通常有两次独立医疗机构选择。','Without a PPP, the worker generally has two independent provider choices.')}</div>{note}</div>
  if (section===6) return <div className="lab-content"><div className="lab-grid"><NumberInput label={pick('平均周薪 AWW ($)','Average weekly wage ($)')} value={wage} set={setWage}/><NumberInput label={pick('因伤缺勤的日历日','Calendar days away')} value={day} set={setDay} max={365}/></div><div className="lab-result big">{money(wage*2/3)} <small>{pick('每周基础公式：AWW × 2/3','weekly base formula: AWW × 2/3')}</small></div><p>{day>=14?pick('达到 14 个日历日：最初三个失去的工作日可能追溯补付。','At 14 calendar days, the first three lost workdays may become payable.'):pick('未达到 14 个日历日：最初三个失去的工作日通常不付。','Below 14 calendar days, the first three lost workdays are generally unpaid.')}</p>{note}</div>
  if (section===7) return <div className="lab-content"><div className="lab-grid"><NumberInput label={pick('原岗位当前周薪 ($)','Current old-job weekly pay ($)')} value={wage} set={setWage}/><NumberInput label={pick('轻工作税前周薪 ($)','Light-duty gross weekly pay ($)')} value={light} set={setLight}/></div><div className="lab-result big">{money((wage-light)*2/3)} <small>{pick('每周 TPD 教学估算','weekly TPD illustration')}</small></div><p>{pick('公式：(原岗位当前收入 − 轻工作收入) × 2/3。2011 年 6 月 28 日前的伤害有不同净收入规则。','Formula: (current old-job pay − light-duty pay) × 2/3. Injuries before June 28, 2011 use a different net-pay rule.')}</p>{note}</div>
  if (section===8) return <div className="lab-content"><p>{pick('康复计划不是一张表：每一步都留下参与证据。','A rehabilitation plan is more than a form. Each step creates evidence of participation.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('无法回原岗位','Cannot return to old job')}</Toggle><Toggle on={b} onChange={setB}>{pick('参加合理计划','Participates in reasonable plan')}</Toggle><Toggle on={c} onChange={setC}>{pick('保存费用与出勤','Keeps costs and attendance')}</Toggle></div><div className="lab-result">{a&&b&&c?pick('治疗／训练的必要性、实际参与和附带费用都有材料可核对。','Need for training, actual participation, and incidental costs are all documented.'):pick('把工作限制、计划、出勤和费用串成可验证的时间线。','Connect restrictions, the plan, attendance, and costs in a verifiable timeline.')}</div></div>
  if (section===9) return <div className="lab-content"><div className="lab-grid"><NumberInput label={pick('平均周薪 AWW ($)','Average weekly wage ($)')} value={wage} set={setWage}/><NumberInput label={pick('法定周数（示例）','Statutory weeks (example)')} value={weeks} set={setWeeks} max={1000}/><NumberInput label={pick('失用比例 (%)','Loss of use (%)')} value={loss} set={setLoss} max={100}/></div><div className="lab-result big">{money(wage*.6*weeks*loss/100)} <small>{pick('部位表公式演示：AWW × 60% × 周数 × 比例','schedule illustration: AWW × 60% × weeks × percentage')}</small></div><p>{pick('先判定适用哪条 PPD 路径，法定周数也随部位和事故日期改变。','First choose the applicable PPD path; statutory weeks depend on the body part and injury date.')}</p>{note}</div>
  if (section===10) return <div className="lab-content"><p>{pick('PTD 不是“做不了原工作”就自动成立。','PTD does not follow automatically from inability to do the old job.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('达到 MMI','Reached MMI')}</Toggle><Toggle on={b} onChange={setB}>{pick('无法做原岗位','Cannot do old job')}</Toggle><Toggle on={c} onChange={setC}>{pick('无法稳定从事任何工作','Cannot sustain any work')}</Toggle></div><div className="lab-result">{a&&c?pick('可能进入 PTD 评估；还须证明持续能力与适用法定标准。','The facts may support PTD review; lasting capacity and the legal standard still need proof.'):b?pick('仅失去原岗位还不够；下一步要评估其他可持续工作。','Loss of the old job alone is insufficient. Evaluate other sustainable work.'):pick('先把治疗阶段和实际工作能力查清。','First establish the treatment stage and actual work capacity.')}</div></div>
  return <div className="lab-content"><p>{pick('改变家庭情况，看遗属顺位与再婚的影响。','Change the family situation to see beneficiary priority and remarriage effects.')}</p><div className="lab-controls"><Toggle on={a} onChange={setA}>{pick('有配偶','Spouse')}</Toggle><Toggle on={b} onChange={setB}>{pick('有未成年子女','Minor child')}</Toggle><Toggle on={c} onChange={setC}>{pick('配偶再婚','Spouse remarries')}</Toggle></div><div className="lab-result">{a&&c&&!b?pick('无合资格子女时，再婚配偶可获相当于两年福利的最后给付。','With no eligible child, the remarried spouse may receive a final two-year-equivalent payment.'):a&&c&&b?pick('仍有合资格子女时，遗属福利继续。','With an eligible child, survivors’ benefits continue.'):a||b?pick('配偶与未成年子女处于主要受益人顺位。','Spouse and minor children are primary beneficiaries.'):pick('没有第一顺位受益人时，才继续查看其他依赖者资格。','Without primary beneficiaries, review other dependents under the statutory order.')}</div>{note}</div>
}

function SourceLine({page}) { return <div className="source-line"><span>{labels.source}：</span><a href={`${handbook}#page=${page}`} target="_blank" rel="noreferrer">{labels.current} · PDF p.{page} ↗</a><span>·</span><a href={sourceIndex} target="_blank" rel="noreferrer">{labels.verify} ↗</a></div> }
function CourtCase({section}) { const item=cases[section]; if(!item)return null;return <aside className="case-panel"><div className="eyebrow">{labels.case}</div><h3>{item.name}</h3><p>{zh?item.zh:item.en}</p><a href={item.url} target="_blank" rel="noreferrer">{item.cite} ↗</a></aside> }
function ScheduleTable(){return <section className="schedule-section"><div className="reading-label"><span>↳</span>{zh?'2024 修订版部位表 · 法定周数':'2024 schedule of body parts · statutory weeks'}</div><p>{zh?'先选事故日期的列，再找部位；周数还须乘失用比例和适用的周费率。':'Choose the injury-date column, then the body part. Multiply weeks by loss percentage and the applicable weekly rate.'}</p><div className="table-scroll"><table><thead><tr><th>{zh?'部位':'Body part'}</th><th>&lt; 7/20/2005</th><th>7/20–11/15/2005</th><th>11/16/2005–1/31/2006</th><th>2/1/2006–6/27/2011</th><th>≥ 6/28/2011</th></tr></thead><tbody>{schedule.map(row=><tr key={row[0]}><th>{zh?row[1]:row[0]}</th>{row.slice(2).map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><small>{zh?'容貌损害：150 / 162 / 150 / 162 / 162 周（按相同日期列）。':'Disfigurement: 150 / 162 / 150 / 162 / 162 weeks for the same date columns.'}</small></section>}
function ChapterStory({chapter}) { const [step,setStep]=useState(0); useEffect(()=>setStep(0),[chapter]); const s=chapters[chapter-1].story;const items=zh?s.zh:s.en;return <section className="story-panel"><div className="section-heading"><span className="eyebrow">{labels.story}</span><h2>{zh?s.zhName:s.enName}</h2></div><div className="story-steps">{items.map((part,i)=><button key={i} type="button" className={'story-step '+(step===i?'active':'')} onClick={()=>setStep(i)}><span className="story-index">0{i+1}</span><strong>{part[0]}</strong></button>)}</div><div key={step} className="story-reveal"><span className="story-line"/><p>{items[step][1]}</p></div><small>{labels.storyNote}</small></section> }

function App() {
  const [route,setRoute]=useState(routeFromHash)
  const [menu,setMenu]=useState(false)
  const [query,setQuery]=useState('')
  const [font,setFont]=useState(()=>Number(localStorage.getItem('iwcc-font')||1))
  const [learned,setLearned]=useState(()=>{try{return JSON.parse(localStorage.getItem('iwcc-learned')||'[]')}catch{return []}})
  useEffect(()=>{const handler=()=>{setRoute(routeFromHash());setMenu(false);window.scrollTo({top:0,behavior:'instant'})};window.addEventListener('hashchange',handler);return()=>window.removeEventListener('hashchange',handler)},[])
  useEffect(()=>{localStorage.setItem('iwcc-font',font)},[font])
  useEffect(()=>{localStorage.setItem('iwcc-learned',JSON.stringify(learned))},[learned])
  const active=route.type==='lesson'?lessons.find(x=>x.id===route.id):null
  const section=active?.section||route.section
  const group=sectionLessons(section)
  const index=active?lessons.findIndex(x=>x.id===active.id):-1
  const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return [];return lessons.filter(x=>[x.id,x.zhTitle,x.enTitle,x.zhSummary,x.enSummary,x.zhDetail,x.enDetail].join(' ').toLowerCase().includes(q)).slice(0,24)},[query])
  const toggleLearned=()=>setLearned(prev=>prev.includes(active.id)?prev.filter(x=>x!==active.id):[...prev,active.id])
  const chapter=chapters[section-1]
  return <div className="site" style={{'--reader-scale':font}}>
    <header className="topbar"><button type="button" className="menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?labels.close:labels.menu}>{menu?'✕':'☰'}</button><button className="brand" onClick={()=>go(chapterPath(1))}><span className="brand-mark">W<span>.</span></span><span><strong>{labels.book}</strong><small>{labels.edition}</small></span></button><div className="top-actions"><span className="top-progress">{learned.length}<span>/94 {labels.learn}</span></span><a href={sibling+window.location.hash} className="language-link">{labels.language} ↗</a></div></header>
    <div className="shell">
      {menu&&<button className="mobile-scrim" aria-label={labels.close} onClick={()=>setMenu(false)}/>}
      <aside className={'sidebar '+(menu?'open':'')}>
        <div className="sidebar-heading"><span className="eyebrow">{labels.chapters}</span><span className="sidebar-count">11 / 94</span></div>
        <label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search}/>{query&&<button onClick={()=>setQuery('')} aria-label="clear">×</button>}</label>
        {query?<div className="search-results"><p>{labels.results} · {results.length}</p>{results.length?results.map(x=><button key={x.id} onClick={()=>{go(lessonPath(x.id));setQuery('')}}><span>{x.id}</span><strong>{title(x)}</strong></button>):<p>{labels.noResults}</p>}</div>:<nav className="chapter-nav">{chapters.map((x,i)=>{const n=i+1;const count=sectionLessons(n).filter(item=>learned.includes(item.id)).length;return <button key={n} className={(section===n?'selected ':'')+(route.type==='chapter'&&section===n?'chapter-active':'')} onClick={()=>go(chapterPath(n))}><span className="nav-number">{String(n).padStart(2,'0')}</span><span className="nav-copy"><strong>{zh?x.zh:x.en}</strong><small>{count}/{sectionLessons(n).length} {labels.learn}</small></span><span className="nav-arrow">↗</span></button>})}</nav>}
        <div className="sidebar-footer"><div className="progress-bar"><span style={{width:`${learned.length/94*100}%`}}/></div><p>{labels.progress} · {learned.length}/94</p></div>
      </aside>
      <main className="main-content">
        {active ? <>
          <div className="breadcrumb"><button onClick={()=>go(chapterPath(section))}>{String(section).padStart(2,'0')} · {zh?chapter.zh:chapter.en}</button><span>/</span><span>{active.id}</span></div>
          <article className="lesson-page" key={active.id}>
            <div className="lesson-head"><span className="eyebrow">{labels.lesson} {active.id} <span className="eyebrow-rule"/></span><h1>{title(active)}</h1><p>{summary(active)}</p></div>
            <div className="article-grid"><div className="article-body"><section className="reading-section"><div className="reading-label"><span>01</span>{labels.rule}</div><div className="reading-prose">{splitCopy(detail(active)).map((p,i)=><p key={i}>{p}</p>)}</div></section>{active.id==='9.2'&&<ScheduleTable/>}<div className="takeaway"><span>↳ {labels.key}</span><p>{summary(active)}</p></div><section className="reading-section application"><div className="reading-label"><span>02</span>{labels.apply}</div><h2>{labels.story}</h2><p>{zh?active.zhExample:active.enExample}</p><small>{zh?'教学情境（虚构）':'Fictional teaching example'}</small><button className="text-link" onClick={()=>go(chapterPath(section))}>{labels.chapter} ↗</button></section><section className="lab-panel"><div className="reading-label"><span>03</span>{labels.interactive}</div><Lab key={section} section={section}/></section>{({'5':'5.9','6':'6.2','8':'8.2'})[section]===active.id&&<CourtCase section={section}/>}<SourceLine page={active.sourcePage}/></div><aside className="lesson-rail"><div className="rail-head"><span className="eyebrow">{String(section).padStart(2,'0')} · {zh?chapter.zh:chapter.en}</span><strong>{group.length} {labels.lines}</strong></div>{group.map(x=><button key={x.id} className={x.id===active.id?'current':''} onClick={()=>go(lessonPath(x.id))}><span>{x.id}</span><span>{title(x)}</span>{learned.includes(x.id)&&<b>✓</b>}</button>)}</aside></div>
            <div className="lesson-actions"><button className={'learn-button '+(learned.includes(active.id)?'learned':'')} onClick={toggleLearned}>{learned.includes(active.id)?'✓ '+labels.learned:'+ '+labels.done}</button><div><button disabled={index===0} onClick={()=>go(lessonPath(lessons[index-1]?.id))}>← {labels.previous}</button><button disabled={index===lessons.length-1} onClick={()=>go(lessonPath(lessons[index+1]?.id))}>{labels.next} →</button></div></div>
          </article>
        </> : <div className="chapter-page" key={section}>
          <div className="chapter-kicker"><span>{String(section).padStart(2,'0')}</span><span>{zh?'章':'CHAPTER'}</span><span className="kicker-line"/></div>
          <div className="chapter-hero"><div><span className="eyebrow">THE FIELD GUIDE / {String(section).padStart(2,'0')}</span><h1>{zh?chapter.zh:chapter.en}</h1><p>{zh?chapter.zhIntro:chapter.enIntro}</p><button className="primary-cta" onClick={()=>go(lessonPath(group[0].id))}>{labels.start} <span>→</span></button></div><div className="chapter-art" aria-hidden="true"><span className="art-circle"/><span className="art-index">{String(section).padStart(2,'0')}</span><span className="art-line one"/><span className="art-line two"/><span className="art-line three"/><span className="art-caption">{group.length} {labels.lines}</span></div></div>
          <ChapterStory chapter={section}/>
          <section className="chapter-lessons"><div className="section-heading"><span className="eyebrow">{labels.overview}</span><h2>{group.length} {labels.lines}</h2></div><div className="lesson-list">{group.map((item,i)=><button key={item.id} onClick={()=>go(lessonPath(item.id))}><span className="lesson-list-number">{item.id}</span><span className="lesson-list-copy"><strong>{title(item)}</strong><small>{summary(item)}</small></span><span className="lesson-list-end">{learned.includes(item.id)?'✓':'↗'}</span></button>)}</div></section>
          <section className="lab-panel chapter-lab"><div className="section-heading"><span className="eyebrow">{labels.interactive}</span><h2>{zh?'先试，再读':'Try it before reading'}</h2></div><Lab key={section} section={section}/></section><CourtCase section={section}/><div className="chapter-pager"><button disabled={section===1} onClick={()=>go(chapterPath(section-1))}>← {labels.prevChapter}</button><button disabled={section===11} onClick={()=>go(chapterPath(section+1))}>{labels.nextChapter} →</button></div>
        </div>}
        <footer className="site-footer"><span>IWCC · {labels.edition}</span><span>{labels.footnote}</span><a href={sourceIndex} target="_blank" rel="noreferrer">{labels.verify} ↗</a><div className="font-switch"><span>{labels.font}</span><button onClick={()=>setFont(Math.max(.9,+(font-.1).toFixed(1)))} aria-label="smaller text">A−</button><button onClick={()=>setFont(Math.min(1.3,+(font+.1).toFixed(1)))} aria-label="larger text">A+</button></div></footer>
      </main>
    </div>
  </div>
}

export default App
