export const chapters = [
  { zh:'制度与保障', en:'Coverage & benefits', zhIntro:'先判断谁受保障、工作与伤情如何相连，再认识七类福利。', enIntro:'Start with coverage and work connection, then learn the seven benefit types.', story:{zhName:'林娜 · 仓库分拣员',enName:'Lina · warehouse picker',zh:[['入职第一天','林娜在伊州仓库开始轮班。工伤保障不等到试用期结束才出现。'],['一次搬运','她搬箱时肩部受伤，医生记录了动作、症状和工作限制。核心问题是伤情与工作是否相关。'],['选择福利','先支付合理必要的医疗；若暂不能工作，再讨论 TTD；若留下永久功能损失，则在稳定后评估 PPD。']],en:[['First shift','Lina starts work at an Illinois warehouse. Coverage can begin on the first day, before a probationary period ends.'],['The lift','She hurts her shoulder while moving a box. The medical record ties the motion, symptoms, and restrictions to work.'],['Which benefit?','Necessary care comes first. TTD may follow if she cannot work; PPD is considered after a permanent condition stabilizes.']]}},
  { zh:'报告伤害', en:'Report an injury', zhIntro:'把员工通知、雇主处理、事故报告与反报复分开看。', enIntro:'Separate worker notice, employer response, accident reporting, and retaliation.', story:{zhName:'林娜 · 事故后的 45 天',enName:'Lina · the first 45 days',zh:[['当天','林娜把事故日期、地点和搬运经过发给主管，并保留消息。'],['接下来','雇主安排急救并通知保险人；她保存医院记录及停工证明。'],['两条记录','雇主向 IWCC 报事故，不等于林娜已经正式立案。她把自己的通知证据单独保存。']],en:[['That day','Lina tells her supervisor the date, place, and lifting event, and keeps the message.'],['Afterward','The employer arranges care and contacts the insurer. Lina keeps the medical note and work restriction.'],['Two records','The employer’s accident report is not Lina’s formal claim. She tracks her own notice separately.']]}},
  { zh:'正式立案', en:'File a claim', zhIntro:'按 2024 修订版学习 CompFile、案件状态与时间限制。', enIntro:'Use the 2024 revision to learn CompFile, case status, and filing limits.', story:{zhName:'林娜 · 从付款到案件号',enName:'Lina · from payment to case number',zh:[['先有付款','保险人支付了部分医疗账单，但拒绝继续支付物理治疗。'],['电子立案','林娜注册 CompFile 并提交索赔申请，取得案件号和提交回执。'],['持续推进','案件进入状态日；她仍须准备证据、请求审理，并留意法定期限。']],en:[['Some bills paid','The carrier pays some bills but rejects more physical therapy.'],['Electronic claim','Lina registers in CompFile, files the application, and saves the case number and receipt.'],['Keep moving','Status calls follow. She must build the record, request a hearing, and watch the filing limits.']]}},
  { zh:'解决争议', en:'Resolve a dispute', zhIntro:'从举证、听证到复核、和解及裁决执行，读懂一条完整路径。', enIntro:'Follow proof, hearing, review, settlement, and enforcement as one path.', story:{zhName:'林娜 · 一份争议病历',enName:'Lina · a disputed medical note',zh:[['争点','雇主承认事故发生，却认为后续肩痛与工作无关。'],['证据','林娜把当日通知、影像、医生意见和工资单按时间排序。'],['抉择','她可让仲裁员决定，也可比较和解条件；最终和解可能关闭未来医疗权利。']],en:[['The dispute','The employer accepts that the event happened but disputes later shoulder symptoms.'],['The record','Lina arranges notice, imaging, medical opinions, and pay records in order.'],['A choice','She can ask an arbitrator to decide or weigh a settlement that may close future medical rights.']]}},
  { zh:'医疗福利', en:'Medical care', zhIntro:'医疗必要性、选医次数、PPP、账单与体检都在这里。', enIntro:'Learn medical necessity, provider choice, PPPs, bills, and examinations.', story:{zhName:'林娜 · 第二位医生',enName:'Lina · a second doctor',zh:[['初诊','急诊先处理肩伤；急诊通常不消耗独立选医次数。'],['持续治疗','她选择骨科医生，按转诊去物理治疗，同时保留医嘱。'],['被拒账单','保险人质疑某次治疗，她收集病历和费用记录，请 IWCC 判断必要性。']],en:[['Urgent care','Emergency treatment comes first and generally does not use an independent provider choice.'],['Ongoing care','She chooses an orthopedist and follows a therapy referral, keeping each order.'],['A denied bill','The carrier questions one treatment. She gathers records and asks the IWCC to decide necessity.']]}},
  { zh:'临时全残 TTD', en:'Temporary total disability', zhIntro:'理解停工起点、平均周薪、等待期和最大医疗改善。', enIntro:'Understand time off work, average weekly wage, the waiting period, and MMI.', story:{zhName:'Jeff Urban · 真实判例',enName:'Jeff Urban · actual court case',zh:[['工伤与轻工作','木工 Jeff Urban 头、颈和背部受伤后做轻工作，后来因与伤情无关的行为被解雇。'],['停止付款','雇主把解雇当作停付 TTD 的理由，争议进入伊州最高法院。'],['法院结果','最高法院认为解雇不会自动结束 TTD；是否达到最大医疗改善仍是关键。']],en:[['Injury and light duty','Carpenter Jeff Urban hurt his head, neck, and back, worked light duty, then was fired for unrelated conduct.'],['Payments stopped','The employer treated the firing as a reason to stop TTD; the dispute reached the Illinois Supreme Court.'],['The holding','Firing did not automatically end TTD. Whether Urban had reached maximum medical improvement remained key.']]}},
  { zh:'临时部分失能 TPD', en:'Temporary partial disability', zhIntro:'用真实数字学恢复期轻工作造成的工资差额。', enIntro:'Use real numbers to see the pay gap during recovery and light duty.', story:{zhName:'林娜 · 改做库存登记',enName:'Lina · assigned to inventory',zh:[['工作限制','医生允许轻工作，仓库安排她坐着登记库存。'],['工资下降','旧岗位现在每周可赚 $925，轻工作每周实际赚 $500。'],['计算补差','两者差 $425；按修订版手册例子，其三分之二是每周 $283.33，仍须核对适用限制。']],en:[['Restriction','Her doctor allows light duty, so the warehouse assigns seated inventory work.'],['Lower pay','The old job now pays $925 weekly; the light-duty job pays $500.'],['The gap','The $425 difference yields $283.33 weekly at two-thirds, subject to the applicable rules.']]}},
  { zh:'职业康复', en:'Vocational rehabilitation', zhIntro:'回不了原岗位时，看再培训、求职计划和维持福利。', enIntro:'When the old job is no longer possible, learn retraining, job search, and maintenance.', story:{zhName:'Craig Kolin · 真实判例',enName:'Craig Kolin · actual court case',zh:[['膝伤','Craig Kolin 因工作受膝伤，开始职业康复计划。'],['费用争议','雇主质疑康复与维持福利；委员会认可其参与和辅导员费用。'],['法院结果','上诉法院维持委员会决定并发回后续程序。案例显示计划合理性和实际参与都需证据。']],en:[['Knee injury','Craig Kolin was injured at work and entered a vocational rehabilitation plan.'],['The dispute','The employer challenged rehabilitation and maintenance. The Commission credited his participation and counselor costs.'],['The result','The appellate court affirmed and remanded. The reasonableness of the plan and evidence of participation mattered.']]}},
  { zh:'永久部分失能 PPD', en:'Permanent partial disability', zhIntro:'伤情稳定后，比较工资差额、部位表、整体身体与容貌损害。', enIntro:'After MMI, compare wage differential, the schedule, whole-person loss, and disfigurement.', story:{zhName:'林娜 · 肩部留下限制',enName:'Lina · lasting shoulder limits',zh:[['达到稳定','治疗结束后，医生认为林娜的肩部已达到 MMI，但仍有活动限制。'],['选择路径','她继续工作，却无法做原来的重搬运；裁决者会看实际工资影响或适用的失用类别。'],['计算与证据','医学报告只是因素之一，还要看职业、年龄、未来收入及病历。不能把所有类别机械相加。']],en:[['MMI','Treatment ends and Lina reaches MMI, but shoulder motion remains limited.'],['Choose a path','She can work but not in the old heavy-lifting role. The award path depends on wage loss or a qualifying impairment category.'],['Proof and math','The medical rating is one factor alongside occupation, age, future earnings, and records. Categories cannot simply be stacked.']]}},
  { zh:'永久全残 PTD', en:'Permanent total disability', zhIntro:'判断是否永久无法在稳定劳动力市场工作，以及后续给付。', enIntro:'Assess permanent inability to work in the stable labor market and ongoing benefits.', story:{zhName:'周先生 · 虚构教学情境',enName:'Mr. Zhou · fictional teaching scenario',zh:[['严重损伤','周先生因工伤失去两只手的使用能力，治疗后仍无法恢复。'],['资格判断','他可能符合手册列举的 PTD 路径；其他案件则须证明无法稳定从事工作。'],['后续变化','福利按平均周薪规则计算；如果工作能力后来明显变化，仍可能重新审查。']],en:[['Severe injury','Mr. Zhou permanently loses use of both hands after a work injury.'],['Eligibility','That may fit a listed PTD route. Other cases require proof that the worker cannot maintain employment in the stable labor market.'],['Later change','Weekly pay follows the AWW rules; a meaningful change in work capacity can prompt review.']]}},
  { zh:'死亡与遗属', en:'Death & survivors', zhIntro:'丧葬费、周福利、受益人顺位和再婚影响分开学习。', enIntro:'Separate burial payment, weekly benefits, beneficiary priority, and remarriage.', story:{zhName:'陈家 · 虚构教学情境',enName:'The Chen family · fictional teaching scenario',zh:[['工作事故','陈先生在工作事故后去世，家属先保存死亡证明与工资记录。'],['两类款项','丧葬费与遗属每周福利分别计算；后者需要平均周薪资料。'],['谁能领取','配偶与未成年子女优先；家庭结构变化时，再婚和子女资格会影响支付。']],en:[['A fatal event','Mr. Chen dies after a work accident. The family keeps death and pay records.'],['Two payments','Burial payment and weekly survivors’ benefits are separate; weekly pay needs AWW evidence.'],['Who receives it','Spouse and minor children come first. Remarriage and child eligibility can change the payment path.']]}}
]

export const cases = {
  5:{name:'Bryon Kawa · Ford Motor Company',cite:'Kawa v. IWCC, 2013 IL App (1st) 120469WC',url:'https://www.illinoiscourts.gov/Resources/08c9de1a-53d2-47fc-b8ea-7e0d35f55c33/1120469WC.pdf',zh:'Kawa 的肩、背、膝治疗及工作关联受到争议。上诉法院撤销委员会关于因果关系、MMI、TTD、医疗和康复的部分结论并发回；平均周薪与罚款部分维持。这个结果不是直接判他最终拿到全部治疗费，而是要求重新按证据审理。',en:'Kawa disputed causation and treatment for shoulder, back, and knee conditions. The appellate court reversed and remanded parts of the Commission’s causation, MMI, TTD, medical, and rehabilitation findings, while affirming the AWW and penalty findings. It did not itself award every disputed bill.'},
  6:{name:'Jeff Urban · Interstate Scaffolding',cite:'Interstate Scaffolding v. IWCC, No. 107852 (Ill. 2010)',url:'https://www.illinoiscourts.gov/files/107852.pdf/opinion',zh:'Urban 工伤后从事轻工作，随后因无关行为被解雇。雇主因此停付 TTD。伊州最高法院确认：解雇本身不会自动终止 TTD，仍需看伤情是否达到 MMI。',en:'Urban worked light duty after injury, then was fired for unrelated conduct. The employer stopped TTD. The Illinois Supreme Court held that the firing itself did not automatically end TTD; MMI remained central.'},
  8:{name:'Craig Kolin · W.B. Olson',cite:'W.B. Olson v. IWCC, 2012 IL App (1st) 113129WC',url:'https://www.illinoiscourts.gov/files/1113129wc.pdf/opinion',zh:'Kolin 膝伤后的职业康复计划及维持福利受到雇主挑战。委员会认可其努力，并裁给维持福利和辅导员费用；上诉法院维持后发回后续程序。',en:'The employer challenged Kolin’s rehabilitation plan and maintenance after a knee injury. The Commission credited his effort and awarded maintenance and counselor costs; the appellate court affirmed and remanded.'}
}
