// Optional chapter review. Each answer points back to the lesson that explains it.
export const quizzes = {
  1:[
    {lesson:'1.4',zhQ:'林娜在公司停车场跌倒。仅凭地点，能否确定属于工伤？',enQ:'Lina falls in the company parking lot. Does location alone prove a covered work injury?',zhOptions:['能，发生在公司就够了','不能，还要分析事故与工作的关系','不能，停车场伤害从不受保障'],enOptions:['Yes, company property is enough','No, examine how the event related to work','No, parking-lot injuries are never covered'],correct:1,zhWhy:'手册要求事故因工作而起并发生在工作过程中；地点只是事实之一。',enWhy:'The handbook asks whether the accident arose out of and in the course of employment; location is one fact.'},
    {lesson:'1.8',zhQ:'仓库已经张贴 IWCC 通知。林娜受伤后，雇主的义务是否完成？',enQ:'The warehouse posted its IWCC notice. Are its duties complete after Lina is hurt?',zhOptions:['是，张贴通知已经足够','不是，还要处理医疗、记录和适用的付款等义务','是，只要员工没正式立案'],enOptions:['Yes, posting is enough','No, care, records, and applicable payment duties remain','Yes, until the worker files a formal claim'],correct:1,zhWhy:'通知牌、事故记录、医疗和福利支付是分别需要履行的事项。',enWhy:'Posting, accident records, medical care, and benefit payments are separate duties.'}
  ],
  2:[
    {lesson:'2.2',zhQ:'口头告诉主管“大约周二在 3 号货架搬箱受伤”，这类通知是否一定无效？',enQ:'Lina orally tells her supervisor she was hurt lifting at aisle 3 on Tuesday. Is that automatically invalid?',zhOptions:['一定无效，必须书面','不一定；能识别大致日期和地点，但留书面记录更易证明','只有医生代通知才有效'],enOptions:['Always invalid; it must be written','Not necessarily; date and place identify it, but written proof helps','Only a doctor may give notice'],correct:1,zhWhy:'手册不把书面形式作为普通事故通知的唯一方式。',enWhy:'The handbook does not make writing the only form of ordinary accident notice.'},
    {lesson:'2.7',zhQ:'雇主已经电子提交事故报告。员工还需考虑自己的索赔申请吗？',enQ:'The employer electronically filed an accident report. Must the worker still consider a claim application?',zhOptions:['要，两份文件作用不同','不用，事故报告自动成为员工索赔','只有雇主同意才能立案'],enOptions:['Yes, the two filings serve different purposes','No, the accident report becomes the worker claim','Only with employer permission'],correct:0,zhWhy:'雇主报告事故不等于员工向 IWCC 申请裁决。',enWhy:'Employer accident reporting is not the worker’s application to the IWCC.'}
  ],
  3:[
    {lesson:'3.1',zhQ:'按照 2024 手册，林娜应怎样正式提交索赔？',enQ:'Under the 2024 handbook, how should Lina formally file?',zhOptions:['把三份纸质申请邮寄给旧地址','注册 CompFile 并电子提交','只把事故告诉主管'],enOptions:['Mail three paper copies to the old address','Register in CompFile and file electronically','Tell her supervisor only'],correct:1,zhWhy:'修订版指向 CompFile；旧纸质流程已过时。',enWhy:'The revision uses CompFile; the old paper-copy process is outdated.'},
    {lesson:'3.7',zhQ:'通常的申请期限，应比较哪两条时间线？',enQ:'Which two timelines generally determine the filing limit?',zhOptions:['入职日和离职日','事故／失能后三年与末次 TTD／医疗付款后两年','第一次看医生和第一次换医生'],enOptions:['Hiring and termination dates','Three years after injury / disablement versus two years after last TTD / medical payment','First and second doctor visits'],correct:1,zhWhy:'手册说多数案件取这两条期限中较晚的一条，特殊案件仍需另查。',enWhy:'The handbook generally uses the later of those deadlines, subject to special cases.'}
  ],
  4:[
    {lesson:'4.4',zhQ:'19(b-1) 更适合哪种情形？',enQ:'Which situation most closely fits 19(b-1)?',zhOptions:['伤后不能工作，又未获医疗或 TTD','已经返工，只争少量旧 TTD','只想计算永久部位表周数'],enOptions:['Unable to work and receiving neither care nor TTD','Back at work, disputing only a small past TTD amount','Calculating only scheduled permanent weeks'],correct:0,zhWhy:'19(b-1) 针对特定紧急医疗／TTD 争议，且有技术性条件。',enWhy:'19(b-1) targets certain urgent medical / TTD disputes and has technical requirements.'},
    {lesson:'4.11',zhQ:'签最终和解前，林娜仍可能需要手术。最需要看哪项条款？',enQ:'Lina may still need surgery before a final settlement. What term matters most?',zhOptions:['合同字号','未来医疗是否保留或关闭','对方律师的办公室地址'],enOptions:['Contract font size','Whether future medical rights remain or close','The opposing lawyer’s office address'],correct:1,zhWhy:'获批准的和解通常会关闭未来权利，保留事项须写清。',enWhy:'Approved settlements usually close future rights unless a reservation is written clearly.'}
  ],
  5:[
    {lesson:'5.4',zhQ:'林娜急诊后由自选骨科医生转诊理疗。通常怎样计算独立选医次数？',enQ:'After emergency care, Lina’s chosen orthopedist refers her to therapy. How are independent choices usually counted?',zhOptions:['急诊和每次转诊都各算一次','急诊和合规转诊一般不占额外选择','员工永远只能见一名医生'],enOptions:['Emergency and each referral count separately','Emergency and qualifying referrals generally do not use extra choices','A worker may see only one doctor'],correct:1,zhWhy:'要区分独立选医链与急救、急诊或符合规则的转诊。',enWhy:'Independent provider chains differ from emergency care and qualifying referrals.'},
    {lesson:'5.9',zhQ:'医生由员工合法选择，保险人仍可争论什么？',enQ:'The worker properly chose a doctor. What may the carrier still dispute?',zhOptions:['具体治疗是否合理必要','该员工是否能阅读病历','任何治疗都必然不能赔'],enOptions:['Whether a particular treatment is reasonably necessary','Whether the worker can read records','That no treatment can ever be covered'],correct:0,zhWhy:'选择医生与治疗必要性是两个独立判断。',enWhy:'Provider choice and medical necessity are separate questions.'}
  ],
  6:[
    {lesson:'6.3',zhQ:'AWW 为 $900 时，未考虑上下限的 TTD 周基础额是多少？',enQ:'With a $900 AWW, what is the TTD weekly base before statutory limits?',zhOptions:['$300','$600','$900'],enOptions:['$300','$600','$900'],correct:1,zhWhy:'TTD 基础公式是 AWW 的三分之二：$900 × 2/3 = $600。',enWhy:'The TTD base is two-thirds of AWW: $900 × 2/3 = $600.'},
    {lesson:'6.2',zhQ:'Jeff Urban 因与工伤无关的行为被解雇。TTD 是否自动终止？',enQ:'Jeff Urban was fired for conduct unrelated to his injury. Did TTD automatically end?',zhOptions:['自动终止','不自动终止，仍要看 MMI 等伤情事实','自动转为 PPD'],enOptions:['It ends automatically','No; MMI and the medical facts still matter','It automatically becomes PPD'],correct:1,zhWhy:'伊州最高法院在 Urban 案中否定了“解雇即自动停付”的做法。',enWhy:'The Illinois Supreme Court rejected automatic termination based solely on the firing.'}
  ],
  7:[
    {lesson:'7.2',zhQ:'旧岗位当前周薪 $925，轻工作税前 $500。TPD 演示值是多少？',enQ:'Old-job current pay is $925, light-duty gross pay is $500. What is the illustrated TPD?',zhOptions:['$141.67','$283.33','$425'],enOptions:['$141.67','$283.33','$425'],correct:1,zhWhy:'差额 $425，乘三分之二约 $283.33。',enWhy:'The $425 gap multiplied by two-thirds is about $283.33.'},
    {lesson:'7.1',zhQ:'员工已达到 MMI，但仍赚得比过去少。还应直接使用恢复期 TPD 吗？',enQ:'A worker has reached MMI but earns less than before. Is recovery-period TPD automatically the right path?',zhOptions:['是，TPD 永远持续','不是，应评估永久福利等后续路径','是，只看工资差即可'],enOptions:['Yes, TPD lasts forever','No, evaluate permanent-benefit paths','Yes, wage difference alone is enough'],correct:1,zhWhy:'TPD 对应仍在康复的轻工作阶段，MMI 后需换一种分析。',enWhy:'TPD addresses lower-paid light duty during healing; after MMI, use a different analysis.'}
  ],
  8:[
    {lesson:'8.1',zhQ:'职业康复只能是一门培训课吗？',enQ:'Must vocational rehabilitation be only a training class?',zhOptions:['是','不是，也可包括求职指导、训练及合理计划','必须完全由员工自费'],enOptions:['Yes','No; counseling, training, and job plans may be included','It is always entirely worker-funded'],correct:1,zhWhy:'手册列出的康复方式不限于课堂培训。',enWhy:'The handbook lists rehabilitation methods beyond classroom training.'},
    {lesson:'8.4',zhQ:'员工的 TTD 周费率为 $600。合格康复期间的维持福利可以低于多少？',enQ:'A worker’s TTD rate is $600 weekly. May qualifying maintenance be lower?',zhOptions:['可以低于 $600','不能低于 $600','一定是 $0'],enOptions:['It may be below $600','It cannot be below $600','It must be $0'],correct:1,zhWhy:'维持福利不得低于 TTD 费率。',enWhy:'Maintenance may not be less than the TTD rate.'}
  ],
  9:[
    {lesson:'9.2',zhQ:'拇指部位表福利的演示公式是哪一个？',enQ:'Which formula illustrates a scheduled thumb award?',zhOptions:['AWW × 60% × 法定周数 × 失用比例','AWW × 2/3 × 缺勤天数','医院账单 × 失用比例'],enOptions:['AWW × 60% × statutory weeks × loss percentage','AWW × 2/3 × days absent','Medical bill × loss percentage'],correct:0,zhWhy:'先按事故日期找部位周数，再乘周费率与失用比例。',enWhy:'Select the statutory weeks by injury date, then apply the weekly rate and loss percentage.'},
    {lesson:'9.3',zhQ:'医生给出 10% 损伤报告。仲裁员可以只凭这一个数字决定吗？',enQ:'A doctor gives a 10% impairment rating. May an arbitrator rely on that number alone?',zhOptions:['可以','不能，还要综合职业、年龄、未来收入和病历等因素','只有雇主同意才可以'],enOptions:['Yes','No; occupation, age, earning capacity, and records also matter','Only with employer permission'],correct:1,zhWhy:'修订版列出五因素，任何单一因素不能独自决定结果。',enWhy:'The revision lists five factors and rejects a single-factor result.'}
  ],
  10:[
    {lesson:'10.1',zhQ:'周先生不能回原工厂，但能稳定从事办公室工作。是否自动符合 PTD？',enQ:'Mr. Zhou cannot return to the plant but can sustain office work. Is PTD automatic?',zhOptions:['自动符合','不自动，还要看整体稳定就业能力','只看工资降了多少'],enOptions:['Automatically','No; overall sustained work capacity matters','Only the wage reduction matters'],correct:1,zhWhy:'不能做原岗位与无法在稳定劳动力市场从事任何工作是不同判断。',enWhy:'Loss of the old job differs from inability to sustain any work.'},
    {lesson:'10.5',zhQ:'领取 PTD 后，员工是否绝不可能同时领取社会保障残疾福利？',enQ:'Does PTD always prevent Social Security disability benefits?',zhOptions:['绝不可能同时领取','符合各自规则时可能同时领取，但社会保障可能抵减','两边一定全额支付'],enOptions:['Never both','Possibly both if eligible, with a possible Social Security offset','Both always pay in full'],correct:1,zhWhy:'两项福利分别判断资格，社会保障可能因工伤款项调整。',enWhy:'Eligibility is separate; Social Security may offset for workers’ compensation.'}
  ],
  11:[
    {lesson:'11.3',zhQ:'陈先生留下配偶和未成年子女。谁处于遗属福利主要顺位？',enQ:'Mr. Chen leaves a spouse and minor child. Who has primary beneficiary priority?',zhOptions:['配偶和未成年子女','任何同姓亲属','雇主选择的人'],enOptions:['Spouse and minor child','Any relative with the same surname','Whoever the employer selects'],correct:0,zhWhy:'配偶与未成年子女是手册列出的主要受益人。',enWhy:'The handbook names the spouse and minor children as primary beneficiaries.'},
    {lesson:'11.4',zhQ:'配偶再婚时仍有合资格子女，遗属福利会怎样？',enQ:'The spouse remarries while an eligible child remains. What happens to survivors’ benefits?',zhOptions:['立刻全部终止','继续','只能领取一次 $8,000'],enOptions:['All benefits end immediately','They continue','Only a one-time $8,000 payment remains'],correct:1,zhWhy:'有合资格子女时，手册说明福利继续。',enWhy:'The handbook says benefits continue while eligible children remain.'}
  ]
}
