// Each diagram describes the rule of its own lesson. The layouts vary by the relationship being taught.
export const visuals = {
 '1.1':['flow','工作相关伤病|法定福利|通常不先问过错','Work-related harm|Statutory benefits|Fault usually not first'],
 '1.2':['split','IWCC：中立裁决|员工／雇主：提交证据','IWCC: neutral decision|Worker / employer: submit proof'],
 '1.3':['stack','伊州受雇|伊州受伤|工作主要在伊州','Hired in Illinois|Injured in Illinois|Work localized in Illinois'],
 '1.4':['decision','发生在工作场所？|因工作而起？|两者都要分析','At the workplace?|Arising from work?|Examine both'],
 '1.5':['timeline','治疗 → 医疗|康复停工 → TTD／TPD|稳定后 → PPD／PTD','Care → medical|Healing → TTD / TPD|After MMI → PPD / PTD'],
 '1.6':['compare','工伤福利：通常不计所得税|普通工资：另按税法处理','Comp benefits: generally not taxable|Wages: separate tax rules'],
 '1.7':['flow','雇主承担责任|保险人或自保支付|不得转嫁保费给员工','Employer responsible|Insurer or self-insurance pays|No premium charged to worker'],
 '1.8':['stack','投保与张贴|事故记录与报告|医疗、付款、反报复','Coverage and posting|Records and reporting|Care, payments, nonretaliation'],
 '1.9':['flow','发现无保险迹象|记录雇主／地址／日期|联系保险主管机关','Possible missing insurance|Record employer / address / date|Contact insurance regulator'],
 '1.10':['compare','没投保 ≠ 没责任|可能有罚款与其他后果','No insurance ≠ no liability|Penalties and other consequences'],
 '1.11':['stack','员工虚报|雇主虚报保费资料|服务方虚收费','Worker misstatement|Employer premium fraud|Provider false billing'],
 '1.12':['decision','证据分歧？|还是故意骗取？|处罚看事实与价值','Evidence dispute?|Intentional fraud?|Penalty turns on facts and value'],
 '1.13':['flow','亲见事实|记录与日期|向调查单位举报','Firsthand facts|Records and dates|Report to fraud unit'],
 '2.1':['flow','员工受伤|通知主管或指定人|保留送达记录','Worker hurt|Notify supervisor or designee|Keep delivery proof'],
 '2.2':['stack','大致日期|事故地点|发生经过','Approximate date|Place|What happened'],
 '2.3':['timeline','事故日 0|普通事故：尽快通知|通常最迟第 45 天','Accident day 0|Notify promptly|Usually by day 45'],
 '2.4':['flow','收到通知|急救／医疗与保险通知|TTD 或书面解释','Notice received|Care and carrier notice|TTD or written explanation'],
 '2.5':['stack','日期／地点|伤情与缺勤|处理经过','Date / place|Injury and absence|Response'],
 '2.6':['timeline','死亡：2 个工作日|缺勤超 3 个预定工作日|Form 45：通常 1 个月内','Death: 2 workdays|Over 3 scheduled days lost|Form 45: generally 1 month'],
 '2.7':['compare','雇主事故报告|员工正式索赔申请','Employer accident report|Worker claim application'],
 '2.8':['flow','张贴 IWCC 通知|员工找到信息|受伤仍须具体通知','Post IWCC notice|Worker finds information|Still report actual injury'],
 '2.9':['decision','缺材料？补齐|正式拒付？准备证据|争议可交 IWCC','Missing records? Supply them|Denied? Build proof|Dispute may go to IWCC'],
 '2.10':['compare','善意行使权利：受保护|合法且无关的解雇理由：另判断','Good-faith claim: protected|Unrelated lawful reason: separate inquiry'],
 '3.1':['flow','注册 CompFile|电子提交申请|保存回执与案号','Register in CompFile|File electronically|Keep receipt and case number'],
 '3.2':['compare','IWCC 表格／立案：$0|病历等准备开支：另算','IWCC forms / filing: $0|Record preparation: separate cost'],
 '3.3':['flow','官方表格页|核对当前版本|CompFile 提交','Official forms page|Check current version|Submit in CompFile'],
 '3.4':['timeline','立案获案号|定期状态日|主动请求听证','Case number|Regular status calls|Request a hearing'],
 '3.5':['flow','案号|CompFile 查询|核对仲裁员与状态','Case number|CompFile search|Check arbitrator and status'],
 '3.6':['compare','雇主自愿付款|IWCC 正式立案：另一条线','Employer pays voluntarily|Formal IWCC filing: separate path'],
 '3.7':['timeline','事故／失能后 3 年|末次医疗／TTD 后 2 年|通常取较晚者','3 years after injury / disablement|2 years after last medical / TTD|Usually the later date'],
 '3.8':['compare','收福利支票|签最终和解：效果不同','Receive a benefit check|Sign final settlement: different effect'],
 '3.9':['split','自行代理：自己举证|聘律师：由律师代理','Self-represented: build your proof|Attorney: professional representation'],
 '3.10':['stack','一般 20% 上限|及时自愿付款通常不计费|协议需批准','General 20% ceiling|Timely voluntary pay usually excluded|Agreement needs approval'],
 '3.11':['flow','记录沟通问题|索取案卷与费用说明|寻求合适渠道','Document concern|Request file and fee detail|Use appropriate channel'],
 '4.1':['flow','提出福利请求|串起事故与医学证据|员工通常承担证明','Ask for benefits|Connect event and medical proof|Worker usually bears burden'],
 '4.2':['stack','管辖／雇佣|工作事故／医学因果|及时通知','Jurisdiction / employment|Work event / causation|Timely notice'],
 '4.3':['timeline','收集记录与证人|仲裁听证|书面决定','Gather records and witnesses|Arbitration hearing|Written decision'],
 '4.4':['compare','19(b)：医疗或补偿争议|19(b-1)：不能工作且缺医疗／TTD','19(b): medical or pay dispute|19(b-1): unable to work without care / TTD'],
 '4.5':['flow','仲裁员决定|期限内申请复核|三名委员审查','Arbitrator decision|Timely review request|Three commissioners review'],
 '4.6':['timeline','仲裁胜诉|雇主复核期间可暂缓|最终维持可能计利息','Arbitration award|Payment may pause on review|Interest may follow final award'],
 '4.7':['flow','委员会决定|巡回法院|后续上诉受期限约束','Commission decision|Circuit court|Further appeal has deadlines'],
 '4.8':['split','确定的和解金额|可能关闭的未来权利','Certain settlement amount|Future rights that may close'],
 '4.9':['compare','继续审理：结果不确定|和解：金额确定但可能放弃未来','Trial: uncertain result|Settlement: certainty with possible release'],
 '4.10':['flow','写明合同条款|双方签署|IWCC 批准','Write contract terms|Parties sign|IWCC approval'],
 '4.11':['stack','未付账单|未来医疗|保留或关闭的权利','Unpaid bills|Future care|Rights kept or closed'],
 '4.12':['compare','私下付款|委员会批准：终局效果不同','Private payment|Commission approval: different finality'],
 '4.13':['split','今天的一次付款|未来多年的潜在福利','Single payment today|Potential years of future benefits'],
 '4.14':['decision','和解？通常终结|裁决？可能追加医疗|变化有法定窗口','Settlement? Usually final|Award? Later care may remain|Change has a legal window'],
 '4.15':['flow','最终裁决|列出欠付金额|执行／罚款申请','Final award|List unpaid sums|Enforcement / penalty petition'],
 '4.16':['stack','通知与地点|病历／工资记录|证人与争点','Notice and venue|Medical / pay records|Witnesses and issues'],
 '5.1':['flow','工伤关联|合理必要治疗|雇主支付','Work connection|Reasonably necessary care|Employer pays'],
 '5.2':['compare','认可账单：雇主付提供者|员工收到催账：先核对','Accepted bill: employer pays provider|Worker billed: investigate'],
 '5.3':['timeline','案件待决|提供者获案件信息|相关催收受限制','Claim pending|Provider receives case details|Related collection restricted'],
 '5.4':['stack','两次独立选择|急救／急诊不占|合规转诊不占','Two independent choices|Emergency does not count|Qualifying referral does not count'],
 '5.5':['flow','雇主设 PPP|书面告知|员工判断网络与退出','Employer has PPP|Written notice|Worker weighs network / opt-out'],
 '5.6':['flow','书面退出 PPP|计作一次选择|再换治疗链先核对','Decline PPP in writing|Uses one choice|Check before new provider chain'],
 '5.7':['flow','选择被拒|提交选择／转诊记录|IWCC 裁定','Choice disputed|Submit choice / referral history|IWCC decides'],
 '5.8':['compare','旧版通知表|IWCC 当前表格','Old PPP notice|Current IWCC form'],
 '5.9':['split','选医合规？|治疗本身合理必要？','Provider choice valid?|Treatment reasonably necessary?'],
 '5.10':['stack','及时就医|告知工作关联|提供相关记录','Seek care promptly|Describe work event|Provide relevant records'],
 '5.11':['flow','宗教治疗请求|书面协议|仍配合规定检查','Faith-based request|Written agreement|Required exams still apply'],
 '5.12':['compare','可限制护士参与问诊|仍提供相关病历','May limit nurse in visit|Still provide relevant records'],
 '5.13':['flow','雇主通知检查|员工合理出席|费用与误工记录','Employer notices exam|Worker reasonably attends|Track costs and lost time'],
 '5.14':['timeline','医生完成报告|双方收到|听证前至少 48 小时','Doctor completes report|Both sides receive it|At least 48 hours before hearing'],
 '5.15':['split','治疗是否必要|收费表决定付款金额','Is care necessary?|Fee schedule sets amount'],
 '6.1':['decision','医生限制工作|有合适轻工作？|无则考虑 TTD','Doctor restricts work|Suitable light duty?|If none, consider TTD'],
 '6.2':['timeline','康复期|返工或达到 MMI|TTD 终点依事实','Healing period|Return or MMI|TTD endpoint depends on facts'],
 '6.3':['formula','平均周薪 AWW|× 2/3|再核对法定上下限','AWW|× 2/3|Then check legal bounds'],
 '6.4':['flow','收集前 52 周工资|处理特殊周数／收入|算 AWW','Collect prior 52 weeks|Handle special weeks / pay|Calculate AWW'],
 '6.5':['timeline','最初 3 个工作日|通常等待期|缺勤满 14 日可追补','First 3 lost workdays|Usually waiting period|14 calendar days may restore pay'],
 '6.6':['timeline','雇主收到通知|14 天内首次 TTD|停付要书面理由','Employer receives notice|First TTD within 14 days|Written reason to stop'],
 '7.1':['timeline','仍在康复|低薪轻工作|回原工作或 MMI 结束','Still healing|Lower-paid light duty|Ends on old work or MMI'],
 '7.2':['formula','旧岗位当前收入 − 轻工作收入|× 2/3|每周 TPD','Current old-job pay − light-duty pay|× 2/3|Weekly TPD'],
 '7.3':['decision','事故日期|≥ 2006-02-01？|再判断 TPD 条件','Injury date|On / after Feb 1, 2006?|Then assess TPD'],
 '8.1':['stack','求职指导|技能训练|再就业计划','Job-search counseling|Skills training|Return-to-work plan'],
 '8.2':['flow','回不了原岗位|合理训练计划|雇主承担必要费用','Cannot return to old job|Reasonable retraining|Employer covers necessary cost'],
 '8.3':['flow','批准康复计划|实际参与|维持福利及附带费用','Approved plan|Actual participation|Maintenance and incidental costs'],
 '8.4':['formula','康复期维持福利|≥ TTD 周费率|核对实际支付','Maintenance during rehab|≥ weekly TTD rate|Check actual payments'],
 '8.5':['decision','事故日期|≥ 2006-02-01？|再核对康复资格','Injury date|On / after Feb 1, 2006?|Then check rehab eligibility'],
 '9.1':['timeline','达到 MMI|留下永久部分损伤|评估 PPD','Reach MMI|Lasting partial impairment|Assess PPD'],
 '9.2':['compare','工资差额／部位表|整体身体／容貌损害','Wage gap / schedule|Whole person / disfigurement'],
 '9.3':['stack','医学损伤报告|职业与年龄|未来收入／病历佐证','Physician rating|Occupation and age|Future earnings / medical proof'],
 '9.4':['compare','过去痛苦：不单独给付|残余疼痛：可影响失能评估','Past suffering: no separate award|Residual pain: may inform impairment'],
 '9.5':['timeline','最终 PPD 裁决|身体状况变化|30 或 60 个月窗口','Final PPD award|Condition changes|30- or 60-month window'],
 '10.1':['decision','只不能做原岗位？|还是不能稳定做任何工作？|后者才可能 PTD','Cannot do old job?|Cannot sustain any work?|Latter may support PTD'],
 '10.2':['formula','AWW|× 2/3|法定上下限与持续条件','AWW|× 2/3|Legal limits and duration'],
 '10.3':['flow','工作能力变化|提交持续能力证据|可能修改 PTD','Work capacity changes|Prove sustained capacity|PTD may change'],
 '10.4':['timeline','PTD 仲裁裁决|适用调整起点|按规则调整','PTD award|Adjustment start date|Rule-based increase'],
 '10.5':['compare','工伤 PTD|社会保障残疾：可能抵减','Workers’ comp PTD|Social Security disability: possible offset'],
 '11.1':['decision','事故发生日期|2006-02-01 前／后|$4,200／$8,000','Injury date|Before / after Feb 1, 2006|$4,200 / $8,000'],
 '11.2':['formula','死者前 52 周 AWW|× 2/3|再核对上下限','Deceased worker’s 52-week AWW|× 2/3|Check legal limits'],
 '11.3':['stack','配偶／未成年子女|无第一顺位再看父母|再看其他依赖者','Spouse / minor children|Then dependent parents|Then other dependents'],
 '11.4':['decision','配偶再婚|仍有合资格子女？|决定继续或最后给付','Spouse remarries|Eligible child remains?|Continue or final payment'],
 '11.5':['timeline','遗属仲裁裁决|核对调整资格|依规则提高周福利','Survivors’ award|Check adjustment eligibility|Rule-based weekly increase']
}
